# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20170917_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='message',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
